export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const LOGIN = "LOGIN";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SET_SIDEBAR_TRUE = "SET_SIDEBAR_TRUE";
export const TOGGLE_MYTEAMS = "TOGGLE_MYTEAMS";
export const SET_MYTEAMS_FALSE = "SET_MYTEAMS_FALSE";
